### ISSUE TITLE
Znaleźć podwozie - poszukać w Botland.pl lub innych sklepach internetowych

### ISSUE THREAD

**Issue by agrabara** [agrabara/pxt-SRV-tank#1]
Szukamy podwozia:
- lista w dedykowanym pliku z linkami do stron i cenami

**Comment by maksgrabara** [comment]
123

**Comment by agrabara** [comment]
[podwozie metalowe ale średnio ładne](https://botland.com.pl/pl/podwozia-robotow/6610-dfrobot-devastator-gasienicowe-podwozie-robota-metalowe-silniki.html?search_query=podwozie&results=64) kosztuje około 380pln

**Comment by agrabara** [comment]
[podwozie z amortyzacją plastik](https://botland.com.pl/pl/podwozia-robotow/7242-light-damping-balance-tank-podwozie-gasienicowe-z-amortyzacja-i-napedem-dc.html?search_query=podwozie&results=64) kosztuje 90pln

**Comment by agrabara** [comment]
[tu jest gotowy czołg z którego możnaby zbudować nasz](https://rc-team.pl/czolgi-rc/35920-heng-long-czolg-german-tauch-panzer-iii-116-dzialko-asg-3849.html#) kosztuje 380pln

[a tutaj filmik jak ten czołg jeździ](https://www.youtube.com/watch?time_continue=229&v=I_3obcUdL3c)
